FROM golang:1.10

RUN go get github.com/go-sql-driver/mysql
RUN go get github.com/pressly/goose
RUN go get github.com/gin-gonic/gin
RUN go get github.com/dgrijalva/jwt-go
RUN go get github.com/go-xorm/xorm
RUN go get golang.org/x/crypto/bcrypt
